version: '3.8'

services:
  postgres:
    image: timescale/timescaledb:latest-pg14
    container_name: crypto_oracle_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-crypto_oracle}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-crypto_oracle_pass}
      POSTGRES_DB: ${POSTGRES_DB:-crypto_oracle}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-crypto_oracle}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: crypto_oracle_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data: 